name: 'all-checks-passed-action'
description: 'A GitHub action that passes when all checks pass'
author: 'Comtravo'
inputs:
  ignore_checks:
    required: false
    description: 'stringified JSON array of checks to ignore'
    default: '[]'
  name:
    required: true
    description: 'Name of this run'
runs:
  using: 'node12'
  main: 'dist/index.js'
