name: 'check_suite'
on: # rebuild any PRs and main branch changes
  check_suite:
    types:
      - completed

jobs:
  check_suite_job: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
