name: 'check_run'
on:
  check_run:
    types:
      - completed

jobs:
  check_suite_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
